---
- name: Install MongoDB Cloud/Ops Manager agent via .deb
  hosts: all
  gather_facts: yes
  tasks:

  - name: "Download MongoDB Agent"
    get_url:
      url: curl -OL https://cloud.mongodb.com/download/agent/automation/mongodb-mms-automation-agent-10.15.0.6425-1.amd64.ubuntu1604.deb
      dest: /home/ubuntu/mongo-agent.deb
      mode: '0440'

  - name: Install Agent .deb package
    apt:
      deb: /home/ubuntu/mongo-agent.deb

  - name: Set Agent Project ID
    tags: etcautomationagentconfig
    become: yes
    become_user: root
    lineinfile:
      path: "/etc/mongodb-mms/automation-agent.conf"
      regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      state: present
    register: etcautomationagentconfig

  - name: Set Agent API Key
    tags: etcautomationagentconfig
    become: yes
    become_user: root
    lineinfile:
      path: "/etc/mongodb-mms/automation-agent.conf"
      regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      state: present
    register: etcautomationagentconfig

  - name: Create a /data directory if it does not exist
    become: yes
    become_user: root
    file:
      path: /data
      state: directory
      mode: '0755'
      recurse: yes
      owner: mongodb
      group: mongodb

  - name: "Enable automation service"
    become: yes
    become_user: root
    service:
      name: mongodb-mms-automation-agent
      enabled: yes
    with_items: "{{groups['all']}}"

  - name: "Start automation service"
    become: yes
    become_user: root
    service: name=mongodb-mms-automation-agent state=started
    with_items: "{{groups['all']}}"