- name: Install nvm via bash script
  hosts: all
  gather_facts: yes
  tasks:
    - name: nvm install script
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
