---
- name: Install MongoDB Ops Manager via .deb
  hosts: all
  gather_facts: yes
  tasks:

  - name: "Install Dependencies via apt"
    become: yes
    become_user: root
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
          - libcurl3-gnutls
          - libcurl4
          - libgssapi-krb5-2
          - libkrb5-dbg
          - libldap-2.4-2
          - libpci3
          - libsasl2-2
          - snmp
          - openssl
          - gnupg
    with_items: "{{groups['all']}}"

  - name: Download .deb
    get_url:
      url: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms_4.2.14.56911.20200603T2242Z-1_x86_64.deb
      dest: /home/ubuntu/
      mode: '0440'

  - name: Install a .deb package
    become: yes
    become_user: root
    apt:
      deb: /home/ubuntu/mongodb-mms_4.2.14.56911.20200603T2242Z-1_x86_64.deb

  - name: "Enable mongodb-mms service"
    become: yes
    become_user: root
    service:
      name: mongodb-mms
      enabled: yes
    with_items: "{{groups['all']}}"

  - name: "Start mongodb-mms"
    become: yes
    become_user: root
    service: name=mongodb-mms state=started
    with_items: "{{groups['all']}}"
